"""empty message

Revision ID: 097803cf999d
Revises: 04afb4c9fc21
Create Date: 2017-03-01 12:59:50.382000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097803cf999d'
down_revision = '04afb4c9fc21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('songs', sa.Column('audio_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'audio_url')
    op.drop_column('albums', 'logo_url')
    # ### end Alembic commands ###
