"""empty message

Revision ID: 4a75e830f296
Revises: 14d76a10995c
Create Date: 2017-03-02 17:40:24.961000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a75e830f296'
down_revision = '14d76a10995c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'albums', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint(None, 'albums', type_='foreignkey')
    op.drop_column('albums', 'user_id')
    # ### end Alembic commands ###
