"""empty message

Revision ID: 7269ba8fb6f0
Revises: 
Create Date: 2017-02-28 19:46:57.954000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7269ba8fb6f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=250), nullable=True),
    sa.Column('album_title', sa.String(length=250), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('album_logo', sa.LargeBinary(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album', sa.Integer(), nullable=True),
    sa.Column('song_title', sa.String(length=250), nullable=True),
    sa.Column('audio_file', sa.LargeBinary(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['album'], ['albums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    op.drop_table('users')
    op.drop_table('albums')
    # ### end Alembic commands ###
